version: "3.7"
services:
  app:
    build:
      args:
        user: polonio
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: app
    container_name: app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - "./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - ./:/var/www
    networks:
      - net-poliniAgenda

  db:
    image: mysql:8.0
    container_name: db-poliniAgenda
    restart: unless-stopped
    env_file:
      - ".env"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - net-poliniAgenda

  nginx:
    image: nginx:alpine
    container_name: nginx-poliniAgenda
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/nginx/ssl:/etc/ssl
      - ./docker/nginx:/etc/nginx/conf.d/
    ports:
      - 80:80
      - 3000:443
    environment:
      - NGINX_HOST=${NGINX_HOST}
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      - net-poliniAgenda
    depends_on:
      - app
      - db

#  memcached:
#    image: memcached:1.6-alpine
#    ports:
#      - "11211:11211"
#    restart: always
#
#  redis:
#    image: redis:7.0-alpine
#    ports:
#      - "6379:6379"
#    restart: always

networks:
  net-poliniAgenda:
    driver: bridge